### ISSUE TITLE
Initialization and default values

### ISSUE THREAD

**Issue by jacargentina** [johnny-quesada-developer/react-native-global-state-hooks#4]
Using GlobalStore example for AsyncStorage in my RN app, I've some problems with having centralized handling for simple settings, as the locale for the app.

I must wait for the user setting for its I18n language to be read from async storage, and just then build its menu, etc.

I 've wrote something like this: 

```tsx
const localeStore = new GlobalStore<string, any>('default', {
  asyncStorageKey: 'locale',
});

const useLocaleStore = localeStore.getHook();

const DataContextWrapper = (props: any): any => {
  // settings
  const locale = useLocaleStore();
  const [localeValue, _, localeMeta] = locale;
  const [localeReal, setLocaleReal] = useState<string | undefined>();

  useEffect(() => {
    if (localeMeta.isAsyncStorageReady) {
      setLocaleReal(
        localeValue === 'default' ? getDefaultLocale() : localeValue
      );
    }
  }, [localeValue, localeMeta]);

...
}
```

On app first install, when there is no setting at all on the Async Storage`isAsyncStorageReady` is always false.

I've seen the testing of it on the sources, and found this:

https://github.com/johnny-quesada-developer/react-native-global-state-hooks/blob/f4f9fed5016ac3dd4a5741f795f72e13dd0e7aae/%40tests/__test__/GlobalStoreAsyc.test.ts#L7

It seems the test is putting a default value on this `fakeAsyncStorage`, which is not something I can easily do in my code.

I can't find a way to make this sequence right: I need `isAsyncStorageReady: true`  and the "default" value to be provided on first app install

Any help would be nice.

**Comment by johnny-quesada-developer** [comment]
Hi @jacargentina ,

Thanks for reaching out! I understand your situation and will take a closer look at the code you shared to see if there's a way to make it work as intended. I will review your code today and let you know if I have any suggestions or solutions for your problem.

Thanks again for using our library and feel free to let me know if you have any further questions or concerns.

**Comment by johnny-quesada-developer** [comment]
Hello Again @jacargentina ,

I hope you're doing well. I wanted to address your question about the **GlobalStore** class and the **isAsyncStorageReady** flag. Just to clarify, the flag is designed to automatically populate after the first data is retrieved from the **asyncstorage**. If the async storage is not available or if there is no data stored in it, the state will use the default value instead. _The purpose of this flag is to differentiate between using the default value and using the stored value._

If you're still experiencing difficulties, please don't hesitate to let me know. I'm happy to take another look or provide additional resources if needed. 

Thank you for reaching out, and I hope we can find a solution to your issue soon.

Best regards

**Comment by jacargentina** [comment]
Ok so…

Back to the case: 
- my app starts with “default” language
- wich is the phone lanuage ( for example english)
- the user selects another language on the app settings ; spanish for example, it is stored on the global store (async storage)


When the app starts:


- language is “default”, english  (1)
- global store reads from async store the user settings…. (Async)
- app menu rendered in english 
- App reads english songs (260 reads on disk….) (1)
- Global store (async) returns the value for spanish
- app menu rendered in spanish
- App reads spanish songs (260 reads on disk….)

So thats the problem; i would like some way to avoid the first block marked with (1)

**Comment by johnny-quesada-developer** [comment]
Hi Javier,

Based on your explanation, it seems like you want to avoid loading the English songs when the app starts in order to save on resources and improve performance. You could use the **isAsyncStorageReady** to determinate whenever or not read the sounds and display an **ActivityIndicator** instead.

I updated the example of the GlobalStore with the AsyncStorage, here you can see a super simple example of how I implemented, Im using and **ActivityIndicator** based on the **isAsyncStorageReady** .

https://user-images.githubusercontent.com/62082152/227571041-c86ca372-5ba0-4f68-b390-278d80dc2e40.mov

Here you also have code example: [todo-list-with-global-hooks](https://github.com/johnny-quesada-developer/todo-list-with-global-hooks.git).

I hope this information is gonna help you, otherwise dont hesitate in reach out back.

**Comment by jacargentina** [comment]
Thanks a lot @johnny-quesada-developer  for taking the time to see my case!

I'll try to play with your example repo and see if I'm using the lib wrong, and get back here to post my results

**Comment by jacargentina** [comment]
Hey @johnny-quesada-developer 

I've tried on my app https://github.com/jacargentina/iResucito; modified it to use expo, and it seems to work.

So I think there is something related to my native "without expo" app, but I'm having a hard time to find the problem. If you have some time and want to clone and debug it? I understand if not.

Anyway, I will continue looking for it cause I love your library for handling these global states

**Comment by jacargentina** [comment]
@johnny-quesada-developer  

This repo is an empty react-native app (no expo) which has the minimal reproduction case. Can u take a look? 

https://github.com/jacargentina/AwesomeProject

**Comment by johnny-quesada-developer** [comment]
Hi @jacargentina I'll take a look 👍

**Comment by johnny-quesada-developer** [comment]
Hi @jacargentina ,

 I apologize for the delay in my response. It has been a busy week. I took a careful look at the repository you shared and the problem seems to be related to how React works.

I updated the example in the documentation to include a small improvement in the GlobalStore with AsyncStorage. Instead of using :

```ts
if (storedItem === null) return; 
``` 

I used the following:

```ts
if (storedItem === null) {
  const isPrimitiveState = isPrimitive(this.state) && !isDate(this.state);

  // This forces React to re-render the component when the state is an object
  return setState(isPrimitiveState ? this.state : {...this.state});
}
```

This will force a re-render when the state is not primitive, which is actually the main issue in your example. **React** performs the following validation when the **GlobalStore** reaches the **AsyncStorage** and tries to set the state value: 

```ts
Object.is(oldState, newState). 
```

If this execution block returns true, **React** will avoid re-rendering the component since the state is the same.

In this case, since we need to know when we are working with the **AsyncStorage** value and not the default one, you could simply use an object as the store value instead of a primitive string:

Insead of:

```ts
const localeStore = new GlobalStore('default', {
    asyncStorageKey: 'locale',
});
```

use:

```ts
const localeStore = new GlobalStore(
  {
    locale: 'default',
  },
  {
    asyncStorageKey: 'locale',
  },
);

```

Then, inside your component, your code will look basically the same:

```ts
// From:
const [locale, setLocale, { isAsyncStorageReady }] = useLocaleStore();

// To, we just use destructuring to get the value:
const [{ locale }, setLocale, { isAsyncStorageReady }] = useLocaleStore();
```

That's it! Since the store value is an object, once we reach the **AsyncStorage** and the state becomes a new object, **React** will re-render and you'll have all the necessary information to continue.

I hope this helps. If you have any further questions, don't hesitate to ask.


https://user-images.githubusercontent.com/62082152/230071330-4f14005f-866f-4487-a406-fefb3aa51a95.mov

**Comment by jacargentina** [comment]
Hi @johnny-quesada-developer  Thanks a lot again for taking time on this.

I partially understand it; "locale" is "default" by default; then async storage reads the "default" again, so the value is the same. (**primitive** value, etc, right)

BUT, then the problem is why `isAsyncStorageReady ` is not going from `false` to `true` ? I can't fully get how it works fine with objects but not primitives, how both things relate to each other?

Maybe you can put more light on my understanding on this.

Again, thank you a lot!

**Comment by jacargentina** [comment]
**UPDATE**: also, with the new GlobalAsycStore.ts (BTW it is missing an "n" letter) I'm having trouble with storing an array, where it has the empty array as the initial value.

```tsx
const brothersStore = new GlobalStore<BrotherContact[], any>([], {
  asyncStorageKey: 'contacts',
});
const useBrothersStore = brothersStore.getHook();
```

```
TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
```

**Comment by johnny-quesada-developer** [comment]
> 

Hello @jacargentina ,

I hope you are doing well. Thank you for your previous message... of course, it will be a pleasure trying to help:

Regarding the first topic, I want to clarify that the metadata was not designed to be reactive, as creating another state just for the purpose of reactivity would be unnecessary in most cases. However, the metadata will be updated every time the hooks are invoked.

As for the second topic, using non-primitive values as state is recommended because React performs a memory comparison to determine if the state has changed, which is not possible with primitive data types such as strings, numbers, booleans, nulls, and symbols. 

```ts
'' === '' // true
true === true // true
1 === 1 // true
{} === {} // false case they are different objects
[] == [] // false 
```

By using non-primitive values, you should not experience any issues with reactivity.

Lastly, I apologize for the oversight in the code, and I have replaced the destructuring for a clone function:
```ts
{ ...this.state } to clone(this.state)
```
<img width="684" alt="image" src="https://user-images.githubusercontent.com/62082152/231042559-131ad750-6d7a-41ad-a116-32ea5bcd2935.png">


The **clone** function will performs a deep clone of the state, ensuring that all objects are brand new and triggering React rendering.

If you have any further questions or concerns, please do not hesitate to let me know. 

Best regards, happy easter!

**Comment by jacargentina** [comment]
Thanks a lot, I think this can be closed now

**Comment by johnny-quesada-developer** [comment]
Thank you you for the feedback 👍💪 @jacargentina

**Comment by chrisvasey** [comment]
Could the way to do this be added to the docs?
I have been hunting for a way to do this for a while now.
Love the package by the way!
**Edit:** Ignore me. There is a great explanation [here](https://github.com/johnny-quesada-developer/react-native-global-state-hooks#extending-the-global-storage).

**Comment by johnny-quesada-developer** [comment]
> Could the way to do this be added to the docs?
> 
> I have been hunting for a way to do this for a while now.
> 
> Love the package by the way!
> 
> **Edit:** Ignore me. There is a great explanation [here](https://github.com/johnny-quesada-developer/react-native-global-state-hooks#extending-the-global-storage).

I'll take care of that, thank you so much for the feedback.

**Comment by johnny-quesada-developer** [comment]
Hi @jacargentina , @chrisvasey ,

The last version of the package 4.0.0 was released, please take a look into the documentation: 
*  [async-storage-with-global-state](https://github.com/johnny-quesada-developer/react-native-global-state-hooks/issues/4)

The classes approach still present in the library but a couple of functions for creating global state and custom global state were added with the intention or simplify some task like the one you guys were describing.

Now you can create **global states** with a functional approach.

```ts
import { createGlobalState } from 'react-native-global-state-hooks';

export const useCount = createGlobalState(0);
```

In the same way, you can create a custom builder that allows you to inject additional functionality, such as **asyncStorage** synchronization, please take a look:

```ts
import { formatFromStore, formatToStore, createCustomGlobalState } = 'react-native-global-state-hooks'

// Optional configuration available for the consumers of the builder
type HookConfig = {
  asyncStorageKey?: string;
};

// This is the base metadata that all the stores created from the builder will have.
type BaseMetadata = {
  isAsyncStorageReady?: boolean;
};

export const createGlobalState = createGlobalStateWithDecoupledFuncs<
  BaseMetadata,
  HookConfig
>({
  /**
   * This function executes immediately after the global state is created, before the invocations of the hook
   */
  onInitialize: async ({ setState, setMetadata }, config) => {
    setMetadata((metadata) => ({
      ...(metadata ?? {}),
      isAsyncStorageReady: null,
    }));

    const asyncStorageKey = config?.asyncStorageKey;
    if (!asyncStorageKey) return;

    const storedItem = (await asyncStorage.getItem(asyncStorageKey)) as string;

    // update the metadata, remember, metadata is not reactive
    setMetadata((metadata) => ({
      ...metadata,
      isAsyncStorageReady: true,
    }));

    if (storedItem === null) {
      return setState((state) => state, { forceUpdate: true });
    }

    const parsed = formatFromStore(storedItem, {
      jsonParse: true,
    });

    setState(parsed, { forceUpdate: true });
  },

  onChange: ({ getState }, config) => {
    if (!config?.asyncStorageKey) return;

    const state = getState();

    const formattedObject = formatToStore(state, {
      stringify: true,
    });

    asyncStorage.setItem(config.asyncStorageKey, formattedObject);
  },
});
```

That's it, now you'll have a custom builder and you could use it just like this:

For creating new global state with **asyncStorage** integration:
```ts
const useLocale = createGlobalState('default', {
  config: {
    asyncStorageKey: 'locale',
  },
});
```

Inside your components:
```tsx
const [locale, setLocale, { isAsyncStorageReady }] = useLocale();

return (<>
  <Text>{isAsyncStorageReady ? locale :  'Loading...'}</Text>
<>);
```

@jacargentina, thank you for reporting the issue with primitive data types. As you can see in the example, the situation has been addressed. Now, the global hooks allow you to force the update of the component, removing the necessity of using objects just to create a different memory reference.

Please let me know if there is anything else I could help.
